x-server-env: &server-env
  # User and group ids that own the files
  # Use `id -u` and `id -g` to get your User ID and Group ID
  GID: 20
  UID: 501
  # Default config
  ENABLE_AUTOPAUSE: true
  MAX_MEMORY: 4G
  MAX_TICK_TIME: -1
  # Default properties
  ENABLE_WHITELIST: true
  ENFORCE_WHITELIST: true
  EULA: true
  SPAWN_PROTECTION: 0

x-backup-env: &backup-env
  BACKUP_INTERVAL: "24h"
  BACKUP_ON_STARTUP: false
  INITIAL_DELAY: 0
  PAUSE_IF_NO_PLAYERS: true
  PRUNE_BACKUPS_COUNT: 4
  PRUNE_BACKUPS_DAYS: -1

services:
  # Use mc-router to run multiple servers on the same external port
  mc_router: 
    image: itzg/mc-router
    restart: always
    depends_on:
      - familycraft
    environment:
      MAPPING: |
        familycraft.minecraft.monroepost.com=familycraft:25565
    ports:
      - "25565:25565"

  # Familycraft 2025-26 server (1.21.6)
  # familycraft.minecraft.monroepost.com
  familycraft:
    image: itzg/minecraft-server
    restart: unless-stopped
    environment:
      <<: *server-env
      # Server version and modpack
      MODPACK_PLATFORM: MODRINTH
      MODRINTH_MODPACK: /modpacks/Familycraft 26.0.0.mrpack
      VERSION: 1.21.6
      # Server properties
      DIFFICULTY: hard
      MOTD: "Familycraft 2025-26 Server"
      PVP: false
      SEED: -3080464673497616365
    volumes:
      - ./data/familycraft26:/data
      - ./modpacks:/modpacks:ro

  backup_familycraft:
    image: itzg/mc-backup
    restart: always
    depends_on:
      familycraft:
        condition: service_healthy
    environment:
      <<: *backup-env
      RCON_HOST: familycraft
    volumes:
      - ./data/familycraft26:/data:ro
      - ./backups/familycraft26:/backups
